### ISSUE TITLE
Wich React Native UI Toolkit are we going to use?

### ISSUE THREAD

**Issue by angelfeliz** [fus-marcom/rcnative#10]
[React native elements](https://github.com/react-native-training/react-native-elements)
[Native Base](https://nativebase.io/)
other....

Note: My personal choice is React native elements

**Comment by JesseRWeigel** [comment]
I don't have experience with either, so I will rely on your suggestion.

Anyone else have an opinion on way or the other?

**Comment by angelfeliz** [comment]
I see native base is already installed, we can keep using it
