### ISSUE TITLE
About the side menu

### ISSUE THREAD

**Issue by angelfeliz** [fus-marcom/rcnative#12]
could the item in the side menu have sub-item e.g like the side menu like the web project franciscan-react?

**Comment by JesseRWeigel** [comment]
Yes, it could.

**Comment by angelfeliz** [comment]
Ok, I will work on that

**Comment by pantharshit00** [comment]
Use nativebase components https://nativebase.io/

I have already integrated it

**Comment by angelfeliz** [comment]
I did use it at first, but the list component of native Base did not what to style as I like, so I did the Side menu with the react-native component but for the rest of the project I will use nativeBase. Also I looked for a list or a component in native base that I can animated the item child of a Item parent when you click it.
