### ISSUE TITLE
Fix navigation margin issue

### ISSUE THREAD

**Issue by pantharshit00** [fus-marcom/rcnative#13]
see this screenshot 

https://drive.google.com/file/d/1zJFJredv3fVkWrwALXOCevYgs_-iZZbt/view

We need some margin using constants

**Comment by angelfeliz** [comment]
Hi @pantharshit00 we can set the constants of the margin using the library EStyleSheet that we are already using in the project. I can do that but I need more detail, you are talking about the margin in the header?

**Comment by pantharshit00** [comment]
I mean the status bar is bleeding through the header.

On 22-Jan-2018 9:20 AM, "Angel Eduardo" <notifications@github.com> wrote:

Hi @pantharshit00 <https://github.com/pantharshit00> we can set the
constants of the margin using the library EStyleSheet that we are already
using in the project. I can do that but I need more detail, you are talking
about the margin in the header?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fus-marcom/rcnative/issues/13#issuecomment-359318037>,
or mute the thread

**Comment by JesseRWeigel** [comment]
Will the solution in the last comment on this issue https://github.com/react-navigation/react-navigation/issues/1168 work?
